# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FVyUTxWBG8b1DNFcSPSm0XbCBjqTeQ-
"""

import torch

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("VRAM:", round(
        torch.cuda.get_device_properties(0).total_memory / 1024**3,
        2
    ), "GB")
else:
    print("GPU bulunamadı!")

!pip install -q -U transformers datasets accelerate evaluate jiwer librosa soundfile

import transformers
import datasets
import accelerate
import evaluate
import jiwer

print("transformers:", transformers.__version__)
print("datasets:", datasets.__version__)
print("accelerate:", accelerate.__version__)

!git clone https://github.com/moized/stt-demo

# Commented out IPython magic to ensure Python compatibility.
# %cd stt-demo

!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/stt-demo
!git pull origin main

from google.colab import drive

drive.mount("/content/drive")

from pathlib import Path

data_path = Path("/content/drive/MyDrive/stt-demo/data")

print(data_path.exists())
print(list(data_path.iterdir()))

from pathlib import Path
import csv
import shutil

PROJECT_DIR = Path("/content/stt-demo")
DATA_DIR = Path("/content/drive/MyDrive/stt-demo/data")
MANIFEST_DIR = PROJECT_DIR / "training" / "manifests"

# Colab içinde projedeki data klasörünü Drive'a bağlayan symlink
project_data = PROJECT_DIR / "data"

if project_data.exists() or project_data.is_symlink():
    if project_data.is_symlink():
        project_data.unlink()
    elif project_data.is_dir():
        shutil.rmtree(project_data)

project_data.symlink_to(DATA_DIR, target_is_directory=True)

print("Project data:", project_data)
print("Exists:", project_data.exists())

train_csv = MANIFEST_DIR / "train.csv"
val_csv = MANIFEST_DIR / "validation.csv"

print("Train manifest:", train_csv.exists())
print("Validation manifest:", val_csv.exists())

print("\nTrain ilk satır:")
with train_csv.open("r", encoding="utf-8-sig") as f:
    print(next(csv.DictReader(f)))

!python training/fine_tune_whisper.py

import torch
import librosa

from transformers import (
    WhisperProcessor,
    WhisperForConditionalGeneration,
)

from pathlib import Path
import csv


PROJECT_DIR = Path("/content/stt-demo")

MODEL_DIR = (
    PROJECT_DIR
    / "training"
    / "models"
    / "whisper-small-finetuned"
)

TEST_CSV = (
    PROJECT_DIR
    / "training"
    / "segments"
    / "test_segments.csv"
)


# ------------------------------------------------------------
# Test kaydı seç
# ------------------------------------------------------------

with TEST_CSV.open(
    "r",
    encoding="utf-8-sig",
    newline=""
) as f:
    test_rows = list(csv.DictReader(f))

row = test_rows[0]

audio_path = PROJECT_DIR / Path(
    row["audio"].replace("\\", "/")
)

reference = row["text"]


# ------------------------------------------------------------
# Model
# ------------------------------------------------------------

device = (
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

processor = WhisperProcessor.from_pretrained(
    str(MODEL_DIR)
)

model = WhisperForConditionalGeneration.from_pretrained(
    str(MODEL_DIR)
).to(device)

model.eval()


# ------------------------------------------------------------
# Audio
# ------------------------------------------------------------

audio, sr = librosa.load(
    str(audio_path),
    sr=16000,
    mono=True,
)


# ------------------------------------------------------------
# Inference
# ------------------------------------------------------------

inputs = processor(
    audio,
    sampling_rate=16000,
    return_tensors="pt",
)

input_features = (
    inputs.input_features.to(device)
)

with torch.no_grad():

    predicted_ids = model.generate(
        input_features,
        language="turkish",
        task="transcribe",
        max_new_tokens=444,
        repetition_penalty=1.1,
        no_repeat_ngram_size=3,
    )


prediction = processor.batch_decode(
    predicted_ids,
    skip_special_tokens=True,
)[0]


# ------------------------------------------------------------
# Result
# ------------------------------------------------------------

print("=" * 80)

print("\nREFERENCE:")
print(reference)

print("\nFINE-TUNED:")
print(prediction)

print("\nAUDIO:")
print(audio_path)

import re
import unicodedata


def normalize_turkish(text: str) -> str:
    """
    ASR evaluation normalization.

    Amaç:
    - Büyük/küçük harf farkını yok say
    - Noktalama işaretlerini kaldır
    - Fazla boşlukları temizle
    - Türkçe karakterleri koru
    """

    text = unicodedata.normalize("NFC", text)

    # Türkçe büyük harfleri açıkça dönüştür
    text = text.replace("İ", "i")
    text = text.replace("I", "ı")
    text = text.lower().strip()

    # Unicode normalization
    text = unicodedata.normalize(
        "NFC",
        text
    )

    # Noktalama işaretlerini kaldır
    text = "".join(
        char
        for char in text
        if not unicodedata.category(char).startswith("P")
    )

    # Fazla boşlukları temizle
    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

import jiwer

reference_norm = normalize_turkish(reference)
prediction_norm = normalize_turkish(prediction)
print(reference_norm)
print(prediction_norm)

wer = jiwer.wer(
    reference_norm,
    prediction_norm
)

cer = jiwer.cer(
    reference_norm,
    prediction_norm
)
print("\nMETRICS")
print(f"WER: {wer:.2%}")
print(f"CER: {cer:.2%}")

import csv
import re
import unicodedata
from pathlib import Path

import torch
import librosa
import jiwer

from transformers import (
    WhisperProcessor,
    WhisperForConditionalGeneration,
)


# ============================================================
# PATHS
# ============================================================

PROJECT_DIR = Path("/content/stt-demo")

TEST_CSV = (
    PROJECT_DIR
    / "training"
    / "segments"
    / "test_segments.csv"
)

BASE_MODEL = "openai/whisper-small"

FINE_MODEL = (
    PROJECT_DIR
    / "training"
    / "models"
    / "whisper-small-finetuned"
)

device = "cuda" if torch.cuda.is_available() else "cpu"


# ============================================================
# TEXT NORMALIZATION
# ============================================================

def normalize_turkish(text: str) -> str:
    """
    Evaluation için normalize eder.

    - Türkçe İ / I dönüşümünü açıkça yönetir
    - Büyük/küçük harf farkını kaldırır
    - Noktalama işaretlerini kaldırır
    - Fazla boşlukları temizler
    - Türkçe karakterleri korur

    NOT:
    Training transcriptlerini değiştirmiyoruz.
    Sadece WER/CER hesaplamasından önce normalize ediyoruz.
    """

    if text is None:
        return ""

    text = text.strip()

    # Unicode normalization
    text = unicodedata.normalize(
        "NFC",
        text
    )

    # Türkçe özel durumlar
    text = text.replace("İ", "i")
    text = text.replace("I", "ı")

    # Diğer karakterler için lowercase
    text = text.lower()

    # Unicode combining mark temizliği
    text = unicodedata.normalize(
        "NFC",
        text
    )

    # Noktalama işaretlerini kaldır
    text = "".join(
        char
        for char in text
        if not unicodedata.category(char).startswith("P")
    )

    # Fazla boşlukları temizle
    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text


# ============================================================
# CSV
# ============================================================

def load_rows(path: Path):

    with path.open(
        "r",
        encoding="utf-8-sig",
        newline=""
    ) as f:

        return list(
            csv.DictReader(f)
        )


# ============================================================
# TRANSCRIPTION
# ============================================================

def transcribe(
    model,
    processor,
    audio_path
):

    audio, _ = librosa.load(
        str(audio_path),
        sr=16000,
        mono=True,
    )

    inputs = processor(
        audio,
        sampling_rate=16000,
        return_tensors="pt",
    )

    with torch.no_grad():

        ids = model.generate(
            inputs.input_features.to(device),

            language="turkish",
            task="transcribe",

            # Whisper special tokens için biraz boşluk bırakıyoruz
            max_new_tokens=444,

            # Önceki repetition problemini azalt
            repetition_penalty=1.1,
            no_repeat_ngram_size=3,
        )

    return processor.batch_decode(
        ids,
        skip_special_tokens=True,
    )[0].strip()


# ============================================================
# LOAD TEST DATA
# ============================================================

rows = load_rows(
    TEST_CSV
)

print("=" * 80)
print("TEST DATA")
print("=" * 80)

print(
    f"Test segmentleri: {len(rows)}"
)


# ============================================================
# LOAD BASE MODEL
# ============================================================

print()
print("Base Whisper yükleniyor...")

base_processor = WhisperProcessor.from_pretrained(
    BASE_MODEL,
    language="turkish",
    task="transcribe",
)

base_model = (
    WhisperForConditionalGeneration
    .from_pretrained(
        BASE_MODEL
    )
    .to(device)
)

base_model.eval()


# ============================================================
# LOAD FINE-TUNED MODEL
# ============================================================

print()
print("Fine-tuned Whisper yükleniyor...")

fine_processor = WhisperProcessor.from_pretrained(
    str(FINE_MODEL)
)

fine_model = (
    WhisperForConditionalGeneration
    .from_pretrained(
        str(FINE_MODEL)
    )
    .to(device)
)

fine_model.eval()


# ============================================================
# EVALUATION
# ============================================================

results = []

all_references = []
all_base_predictions = []
all_fine_predictions = []

for i, row in enumerate(
    rows,
    start=1
):

    audio_path = PROJECT_DIR / Path(
        row["audio"].replace(
            "\\",
            "/"
        )
    )

    reference = row["text"]

    # --------------------------------------------------------
    # Predictions
    # --------------------------------------------------------

    base_prediction = transcribe(
        base_model,
        base_processor,
        audio_path,
    )

    fine_prediction = transcribe(
        fine_model,
        fine_processor,
        audio_path,
    )

    # --------------------------------------------------------
    # Raw
    # --------------------------------------------------------

    reference_norm = normalize_turkish(
        reference
    )

    base_norm = normalize_turkish(
        base_prediction
    )

    fine_norm = normalize_turkish(
        fine_prediction
    )

    # --------------------------------------------------------
    # Per-segment metrics
    # --------------------------------------------------------

    base_wer = jiwer.wer(
        reference_norm,
        base_norm,
    )

    fine_wer = jiwer.wer(
        reference_norm,
        fine_norm,
    )

    base_cer = jiwer.cer(
        reference_norm,
        base_norm,
    )

    fine_cer = jiwer.cer(
        reference_norm,
        fine_norm,
    )

    # --------------------------------------------------------
    # Store normalized texts for MICRO aggregation
    # --------------------------------------------------------

    all_references.append(
        reference_norm
    )

    all_base_predictions.append(
        base_norm
    )

    all_fine_predictions.append(
        fine_norm
    )

    results.append({
        "id": row["id"],

        "base_wer": base_wer,
        "fine_wer": fine_wer,

        "base_cer": base_cer,
        "fine_cer": fine_cer,
    })

    print(
        f"[{i}/{len(rows)}] "
        f"{row['id']} | "
        f"Base WER={base_wer:.2%} | "
        f"Fine WER={fine_wer:.2%} | "
        f"Base CER={base_cer:.2%} | "
        f"Fine CER={fine_cer:.2%}"
    )
    print(f"fine_norm: {fine_norm}")
    print(f"reference_norm : {reference_norm}")
    print(f"base_norm : {base_norm}")
    print("=" * 80)


print()
print("=" * 80)


# ============================================================
# MICRO-AVERAGED METRICS
# ============================================================

base_wer_micro = jiwer.wer(
    all_references,
    all_base_predictions,
)

fine_wer_micro = jiwer.wer(
    all_references,
    all_fine_predictions,
)

base_cer_micro = jiwer.cer(
    all_references,
    all_base_predictions,
)

fine_cer_micro = jiwer.cer(
    all_references,
    all_fine_predictions,
)


# ============================================================
# MACRO-AVERAGED METRICS
# ============================================================

base_wer_macro = sum(
    r["base_wer"]
    for r in results
) / len(results)

fine_wer_macro = sum(
    r["fine_wer"]
    for r in results
) / len(results)

base_cer_macro = sum(
    r["base_cer"]
    for r in results
) / len(results)

fine_cer_macro = sum(
    r["fine_cer"]
    for r in results
) / len(results)


# ============================================================
# FINAL REPORT
# ============================================================

print()
print("=" * 80)
print("TEST SONUCU")
print("=" * 80)

print()
print("MICRO-AVERAGE")
print("-" * 80)

print(
    f"Base WER       : {base_wer_micro:.2%}"
)

print(
    f"Fine-tuned WER : {fine_wer_micro:.2%}"
)

print(
    f"Base CER       : {base_cer_micro:.2%}"
)

print(
    f"Fine-tuned CER : {fine_cer_micro:.2%}"
)

print()
print("MACRO-AVERAGE")
print("-" * 80)

print(
    f"Base WER       : {base_wer_macro:.2%}"
)

print(
    f"Fine-tuned WER : {fine_wer_macro:.2%}"
)

print(
    f"Base CER       : {base_cer_macro:.2%}"
)

print(
    f"Fine-tuned CER : {fine_cer_macro:.2%}"
)

from pathlib import Path

model_dir = Path(
    "/content/stt-demo/training/models/whisper-small-finetuned"
)

print("Exists:", model_dir.exists())

for p in sorted(model_dir.iterdir()):
    print(p.name, f"({p.stat().st_size / 1024 / 1024:.1f} MB)")

import torch
from transformers import WhisperProcessor, WhisperForConditionalGeneration
import librosa

model_dir = "/content/stt-demo/training/models/whisper-small-finetuned"

processor = WhisperProcessor.from_pretrained(model_dir)

model = WhisperForConditionalGeneration.from_pretrained(
    model_dir
)

model = model.to(
    "cuda" if torch.cuda.is_available() else "cpu"
)

audio_path = "/content/stt-demo/training/segments/audio/test/02_2026-07-01_0m22s_part_001.wav"

audio, sr = librosa.load(
    audio_path,
    sr=16000,
    mono=True
)

inputs = processor(
    audio,
    sampling_rate=16000,
    return_tensors="pt"
)

input_features = inputs.input_features.to(model.device)

with torch.no_grad():
    predicted_ids = model.generate(
        input_features
    )

text = processor.batch_decode(
    predicted_ids,
    skip_special_tokens=True
)[0]

print(text)

# Commented out IPython magic to ensure Python compatibility.
# %ls /content/stt-demo/training/segments/audio/test

from pathlib import Path
import csv

PROJECT_DIR = Path("/content/stt-demo")

test_csv = (
    PROJECT_DIR
    / "training"
    / "segments"
    / "test_segments.csv"
)

with test_csv.open("r", encoding="utf-8-sig", newline="") as f:
    rows = list(csv.DictReader(f))

row = rows[0]

audio_path = PROJECT_DIR / Path(
    row["audio"].replace("\\", "/")
)

reference = row["text"]

print("ID:", row["id"])
print("Audio:", audio_path)
print("Reference:")
print(reference)

import torch
import librosa
from transformers import WhisperProcessor, WhisperForConditionalGeneration

device = "cuda" if torch.cuda.is_available() else "cpu"

base_processor = WhisperProcessor.from_pretrained(
    "openai/whisper-small",
    language="turkish",
    task="transcribe",
)

base_model = WhisperForConditionalGeneration.from_pretrained(
    "openai/whisper-small"
).to(device)

audio, sr = librosa.load(
    str(audio_path),
    sr=16000,
    mono=True,
)

inputs = base_processor(
    audio,
    sampling_rate=16000,
    return_tensors="pt",
)

with torch.no_grad():
    predicted_ids = base_model.generate(
        inputs.input_features.to(device),
        language="turkish",
        task="transcribe",
        max_new_tokens=444,
    )

base_text = base_processor.batch_decode(
    predicted_ids,
    skip_special_tokens=True,
)[0]

print("BASE WHISPER:")
print(base_text)

fine_model_dir = (
    "/content/stt-demo/training/models/whisper-small-finetuned"
)

fine_processor = WhisperProcessor.from_pretrained(
    fine_model_dir,
)

fine_model = WhisperForConditionalGeneration.from_pretrained(
    fine_model_dir
).to(device)

fine_inputs = fine_processor(
    audio,
    sampling_rate=16000,
    return_tensors="pt",
)

with torch.no_grad():
    fine_predicted_ids = fine_model.generate(
        fine_inputs.input_features.to(device),
        language="turkish",
        task="transcribe",
        max_new_tokens=444,
        repetition_penalty=1.1,
        no_repeat_ngram_size=3,
    )

fine_text = fine_processor.batch_decode(
    fine_predicted_ids,
    skip_special_tokens=True,
)[0]

print("FINE-TUNED WHISPER:")
print(fine_text)

!pip install -q jiwer

import jiwer

base_wer = jiwer.wer(reference, base_text)
fine_wer = jiwer.wer(reference, fine_text)

base_cer = jiwer.cer(reference, base_text)
fine_cer = jiwer.cer(reference, fine_text)

print("=" * 60)
print("RESULT")
print("=" * 60)

print(f"Base WER      : {base_wer:.2%}")
print(f"Fine-tuned WER: {fine_wer:.2%}")

print(f"Base CER      : {base_cer:.2%}")
print(f"Fine-tuned CER: {fine_cer:.2%}")

print("=" * 80)

print("\nREFERENCE:")
print(reference)

print("\nBASE:")
print(base_text)

print("\nFINE-TUNED:")
print(fine_text)

print("\nMETRICS:")
print(f"Base      WER={base_wer:.2%} | CER={base_cer:.2%}")
print(f"Fine-tuned WER={fine_wer:.2%} | CER={fine_cer:.2%}")