# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FVyUTxWBG8b1DNFcSPSm0XbCBjqTeQ-
"""

import torch

print("PyTorch Sürümü:", torch.__version__)
print("CUDA Erişilebilir mi?:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print(
        "VRAM:",
        round(
            torch.cuda.get_device_properties(0).total_memory / 1024**3, 2
        ),
        "GB",
    )
else:
    print("[UYARI] GPU bulunamadı! Runtime > Change runtime type > GPU seçin.")

!pip install -q -U transformers datasets accelerate evaluate jiwer librosa soundfile

import os
import shutil
from pathlib import Path
from google.colab import drive

# 1. Drive Mount
drive.mount("/content/drive")

# Çalışma dizinini silinmeyecek güvenli alana çek
os.chdir("/content")

PROJECT_DIR = Path("/content/stt-demo")
DRIVE_DATA_DIR = Path("/content/drive/MyDrive/stt-demo/data")
DRIVE_MODELS_DIR = Path("/content/drive/MyDrive/stt-demo/models")

# Drive yol kontrolü
if not DRIVE_DATA_DIR.exists():
    print("=" * 80)
    print(f"[HATA] Drive üzerinde ses verileri bulunamadı: {DRIVE_DATA_DIR}")
    print(
        "Lütfen Google Drive'ınızda 'stt-demo/data' klasör yapısının olduğunu kontrol edin."
    )
    print("=" * 80)
else:
    # Drive'da models klasörünü hazırla
    DRIVE_MODELS_DIR.mkdir(parents=True, exist_ok=True)

    # 2. Eski reponun temizlenip GitHub'dan sıfırdan çekilmesi
    if PROJECT_DIR.exists():
        shutil.rmtree(PROJECT_DIR)

    !git clone https://github.com/moized/stt-demo /content/stt-demo

    # Proje dizinine güvenli geçiş
    os.chdir(PROJECT_DIR)

    # 3. Data Klasörü Bağlantısı (Symlink)
    project_data = PROJECT_DIR / "data"
    if project_data.exists() or project_data.is_symlink():
        if project_data.is_symlink():
            project_data.unlink()
        elif project_data.is_dir():
            shutil.rmtree(project_data)

    project_data.symlink_to(DRIVE_DATA_DIR, target_is_directory=True)

    # 4. Models Klasörü Bağlantısı (Symlink)
    project_models = PROJECT_DIR / "training" / "models"
    project_models.parent.mkdir(parents=True, exist_ok=True)

    if project_models.exists() or project_models.is_symlink():
        if project_models.is_symlink():
            project_models.unlink()
        elif project_models.is_dir():
            shutil.rmtree(project_models)

    project_models.symlink_to(DRIVE_MODELS_DIR, target_is_directory=True)

    print("\n" + "=" * 80)
    print("✓ Kodlar GitHub'dan başarıyla çekildi.")
    print("✓ Data ve Models bağlantıları kuruldu.")
    print("=" * 80)

!python training/prepare_dataset.py
!python training/split_dataset.py
!python training/segment_dataset.py

!python training/train_whisper.py

!pip install -q ctranslate2

!python convert_to_ctranslate2.py

# Commented out IPython magic to ensure Python compatibility.
# Proje dizinine geçiş yap ve en son değişiklikleri çek
# %cd /content/stt-demo
!git pull origin main

!python training/evaluate_test_set.py